# Generated by Django 3.0.5 on 2020-05-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.IntegerField(max_length=9)),
                ('password', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('telefono', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='tabla_test',
        ),
    ]
