# Generated by Django 3.0.5 on 2020-05-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20200513_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
