# Generated by Django 3.0.5 on 2020-05-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20200513_2347'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginapppersona',
            table=None,
        ),
    ]
